export const PRODUCT_DETAILS = 'PRODUCT_DETAILS';
export const INITIAL_CONFIG = 'INITIAL_CONFIG'
export const IS_NO_ITEMS = 'IS_NO_ITEMS'
export const PRODUCT_ERROR = 'PRODUCT_ERROR'
export const IS_LOADING = 'IS_LOADING'